name: Build Archbang ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Update packages and install archiso
        run: pacman -Syu --noconfirm archiso mkinitcpio-archiso git squashfs-tools

      - name: Build ISO
        run: |
          pacman -S --noconfirm --needed archlinux-keyring wget
          mkarchiso -v -w ./work -o ./out ./
          echo "ISO Built in ./out folder!"
        
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.DATE }}
          prerelease: false
          title: "Archbang"
          files: |
            out/*
            
